name: py build project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pybuildjob1:
    runs-on: ubuntu-latest
    steps:
      - name: pybuildstep1
        uses: actions/checkout@v4
      - name: pybuildstep2
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: running test case
        run: pytest
        continue-on-error: true 
      - name : checking the skipped error
        run: echo Checking the Skipped error
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: build docker image
        run: |
          set -x
          docker version
          docker build -t suresh11593/firstdockerimage .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker push
        run: docker push suresh11593/firstdockerimage
